# Generated by Django 4.2.16 on 2025-11-30 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'permissions': [('can_manage_invoices', 'Puede gestionar facturas'), ('can_view_invoices', 'Puede ver facturas')], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
    ]
