# Generated by Django 4.2.16 on 2025-09-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toastingprocess',
            name='current_humidity_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Humedad actual (%)'),
        ),
        migrations.AddField(
            model_name='toastingprocess',
            name='current_temperature_celsius',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Temperatura actual (°C)'),
        ),
        migrations.AddField(
            model_name='toastingprocess',
            name='current_time_elapsed_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Tiempo transcurrido (min)'),
        ),
        migrations.AddField(
            model_name='toastingprocess',
            name='current_weight_loss_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pérdida de peso actual (kg)'),
        ),
        migrations.AddField(
            model_name='toastingprocess',
            name='equipment_capacity_kg',
            field=models.PositiveIntegerField(default=200, verbose_name='Capacidad del equipo (kg)'),
        ),
        migrations.AddField(
            model_name='toastingprocess',
            name='estimated_time_minutes',
            field=models.PositiveIntegerField(default=15, verbose_name='Tiempo estimado (min)'),
        ),
        migrations.AddField(
            model_name='toastingprocess',
            name='final_grain_quality',
            field=models.CharField(blank=True, choices=[('excellent', 'Excelente'), ('good', 'Buena'), ('regular', 'Regular'), ('poor', 'Deficiente')], max_length=20, null=True, verbose_name='Calidad final del grano'),
        ),
        migrations.AddField(
            model_name='toastingprocess',
            name='final_quality_notes',
            field=models.TextField(blank=True, verbose_name='Notas finales de calidad'),
        ),
        migrations.AddField(
            model_name='toastingprocess',
            name='initial_temperature_celsius',
            field=models.DecimalField(decimal_places=1, default=150.0, max_digits=5, verbose_name='Temperatura inicial (°C)'),
        ),
        migrations.AddField(
            model_name='toastingprocess',
            name='process_status',
            field=models.CharField(choices=[('received', 'Recibido'), ('started', 'Iniciado'), ('monitoring', 'Monitoreando'), ('completed', 'Completado')], default='received', max_length=20, verbose_name='Estado del proceso'),
        ),
        migrations.AddField(
            model_name='toastingprocess',
            name='quality_samples',
            field=models.JSONField(default=dict, verbose_name='Muestras de calidad'),
        ),
        migrations.AddField(
            model_name='toastingprocess',
            name='target_temperature_celsius',
            field=models.DecimalField(decimal_places=1, default=200.0, max_digits=5, verbose_name='Temperatura objetivo (°C)'),
        ),
        migrations.AddField(
            model_name='toastingprocess',
            name='toasting_equipment',
            field=models.CharField(choices=[('industrial_200kg', 'Industrial 200kg'), ('industrial_500kg', 'Industrial 500kg'), ('artisanal_50kg', 'Artesanal 50kg'), ('experimental_10kg', 'Experimental 10kg')], default='industrial_200kg', max_length=30, verbose_name='Equipo de tostión'),
        ),
        migrations.AlterField(
            model_name='toastingprocess',
            name='grain_quality',
            field=models.CharField(blank=True, choices=[('excellent', 'Excelente'), ('good', 'Buena'), ('regular', 'Regular'), ('poor', 'Deficiente')], max_length=20, null=True, verbose_name='Calidad del grano'),
        ),
        migrations.AlterField(
            model_name='toastingprocess',
            name='quality_notes',
            field=models.TextField(blank=True, verbose_name='Notas de calidad'),
        ),
        migrations.AlterField(
            model_name='toastingprocess',
            name='temperature_celsius',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Temperatura (°C)'),
        ),
        migrations.AlterField(
            model_name='toastingprocess',
            name='toasting_time_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tiempo de tostión (min)'),
        ),
    ]
