# Generated by Django 4.2.16 on 2025-11-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_invoice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_coffee_type',
            field=models.CharField(blank=True, choices=[('cps', 'CPS (Café Pergamino Seco)'), ('excelso', 'Excelso')], max_length=20, null=True, verbose_name='Tipo de café original (recepción)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coffee_type',
            field=models.CharField(choices=[('cps', 'CPS (Café Pergamino Seco)'), ('excelso', 'Excelso')], default='excelso', max_length=20, verbose_name='Tipo de café'),
        ),
    ]
