# Generated by Django 4.2.16 on 2025-09-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250923_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toastingprocess',
            name='grain_quality',
        ),
        migrations.RemoveField(
            model_name='toastingprocess',
            name='quality_notes',
        ),
        migrations.RemoveField(
            model_name='toastingprocess',
            name='temperature_celsius',
        ),
        migrations.RemoveField(
            model_name='toastingprocess',
            name='toasting_time_minutes',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('client_create', 'Creación de cliente'), ('client_update', 'Actualización de cliente'), ('order_create', 'Creación de pedido'), ('order_update', 'Actualización de pedido'), ('toasting_start', 'Inicio de tostión'), ('toasting_complete', 'Tostión completada'), ('production_start', 'Inicio de producción'), ('production_complete', 'Producción completada'), ('invoice_create', 'Creación de factura'), ('invoice_payment', 'Pago de factura'), ('company_create', 'Creación de empresa'), ('company_suspend', 'Empresa suspendida'), ('company_activate', 'Empresa activada'), ('user_create', 'Creación de usuario'), ('user_update', 'Actualización de usuario')], max_length=30, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='toastingprocess',
            name='quality_samples',
            field=models.JSONField(blank=True, default=dict, verbose_name='Muestras de calidad'),
        ),
    ]
